### ISSUE TITLE
Instructions for lmplot Example - remove quotes around 'tips'

### ISSUE THREAD

**Issue by JonSolow** [learn-co-curriculum/dsc-seaborn-lab#1]
In the cell with instructions for how to graph the first regression plot, the instructions say to set `data='tips'` as a string, rather than referencing the dataframe called tips (i.e. `data=tips` )

Currently:

Now that we have our dataset, we can create our regression plot. There are several kinds of regression plots we can use. For this example, we'll use the `lmplot` function. 

In the cell below: 

* Call Seaborn's `lmplot` function and pass in the following arguments:
    * `x='total_bill'`
    * `y='tip'`
    * `hue='smoker'`
    * `data='tips'`

**Comment by fpolchow** [comment]
thank you for flagging, it has been fixed!
